FROM node:18-alpine

WORKDIR /app

COPY next-shadcn-admin-dashboard/package.json next-shadcn-admin-dashboard/pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

COPY next-shadcn-admin-dashboard .

RUN pnpm build

EXPOSE 3000

CMD ["pnpm", "start"]