version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
    volumes:
      - ./.env:/app/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./next-shadcn-admin-dashboard
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_WS_URL=ws://backend:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
